modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "cavedust"
version = "${version}"
displayName = "Cave Dust"
authors = "LizIsTired"
description = '''
Makes dust underground that scales with depth!
'''
#logoFile = ""

[[dependencies.cavedust]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cavedust]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cavedust]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"