name: build-release

on:
  release:
    types:
      - published

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x gradlew

      - name: Build Release
        run: ./gradlew build --stacktrace

      - name: Retrieve Version
        id: gradle_version
        run: |
          echo "::set-output name=VERSION_NAME::$(./gradlew -q :common:printVersionName)"


      - name: Upload artifacts to Modrinth, Curseforge and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: jawg7zT1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 594750
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/*.jar
            forge/build/libs/*.jar